apiVersion: v2
name: CHANGEME
description: A Helm chart for CHANGEME
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.0
