#!/usr/bin/env python3
"""Regenerate or verify the pricing section of ``references/api_notes.md``.

This script is the enforcement point of the pricing SSOT described in
the plan (§5.1). It reads the live values from :mod:`lib.pricing` and
re-emits the Markdown table wrapped between the two banner comments:

.. code-block:: markdown

    <!-- GENERATED:PRICING:START -->
    ... table ...
    <!-- GENERATED:PRICING:END -->

Two modes:

``--check``
    Regenerate the block in memory and diff against the committed
    file. Exit 0 on byte-identical match, exit 1 with a unified diff
    on drift. This is the mode wired into CI.

(no flag)
    Rewrite the file in place.

``api_notes.md`` must already contain both banners; if either is
missing the script exits 2 with an actionable error.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

# Support running as ``python scripts/lib/_gen_api_notes_pricing.py``
# and as ``python -m lib._gen_api_notes_pricing``.
if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    from lib.pricing import MODELS  # type: ignore[no-redef]
else:
    from .pricing import MODELS

BANNER_START = "<!-- GENERATED:PRICING:START -->"
BANNER_END = "<!-- GENERATED:PRICING:END -->"

API_NOTES_PATH = (
    Path(__file__).resolve().parent.parent.parent
    / "references"
    / "api_notes.md"
)


def _render_pricing_block() -> str:
    """Render the generated pricing block (banners included).

    Returns
    -------
    str
        Markdown block terminated by a trailing newline. The table
        iterates :data:`lib.pricing.MODELS` in sorted key order so
        regeneration is deterministic.
    """
    lines = [
        BANNER_START,
        "<!-- Regenerated by scripts/lib/_gen_api_notes_pricing.py; "
        "do not edit this block manually. -->",
        "",
        "| Model | Input $/1M tokens | Output $/1M tokens | Model ID |",
        "| :---- | ----------------: | -----------------: | :------- |",
    ]
    for key in sorted(MODELS.keys()):
        model = MODELS[key]
        lines.append(
            f"| {model.name} | {model.input_usd_per_1m:.2f} | "
            f"{model.output_usd_per_1m:.2f} | `{model.id}` |"
        )
    lines.append("")
    lines.append(BANNER_END)
    return "\n".join(lines) + "\n"


def _splice(current: str, new_block: str) -> str:
    """Replace the pricing block in ``current`` with ``new_block``.

    Parameters
    ----------
    current : str
        Current file contents.
    new_block : str
        Fully rendered block (includes banners and trailing newline).

    Returns
    -------
    str
        Updated file contents.

    Raises
    ------
    SystemExit
        With code 2 if either banner is missing.
    """
    start_idx = current.find(BANNER_START)
    end_idx = current.find(BANNER_END)
    if start_idx == -1 or end_idx == -1 or end_idx < start_idx:
        print(
            f"ERROR: banners {BANNER_START!r} / {BANNER_END!r} not found "
            f"in {API_NOTES_PATH}",
            file=sys.stderr,
        )
        raise SystemExit(2)
    end_idx += len(BANNER_END)
    # Consume an optional trailing newline after the end banner so we do
    # not accumulate blank lines on every regeneration.
    if end_idx < len(current) and current[end_idx] == "\n":
        end_idx += 1
    # Strip the trailing newline we'll reintroduce via new_block.
    return current[:start_idx] + new_block + current[end_idx:]


def _cmd_check() -> int:
    """Run the ``--check`` mode. Return a shell exit code."""
    current = API_NOTES_PATH.read_text(encoding="utf-8")
    expected = _splice(current, _render_pricing_block())
    if current == expected:
        return 0
    diff = difflib.unified_diff(
        current.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=str(API_NOTES_PATH),
        tofile=f"{API_NOTES_PATH} (regenerated)",
    )
    sys.stdout.writelines(diff)
    return 1


def _cmd_write() -> int:
    """Run the default (in-place) mode. Return a shell exit code."""
    current = API_NOTES_PATH.read_text(encoding="utf-8")
    expected = _splice(current, _render_pricing_block())
    if current != expected:
        API_NOTES_PATH.write_text(expected, encoding="utf-8")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Entry point.

    Parameters
    ----------
    argv : list of str or None
        CLI arguments (defaults to :data:`sys.argv[1:]`).

    Returns
    -------
    int
        Shell exit code.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Regenerate or verify the pricing section of "
            "references/api_notes.md."
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Diff against the committed file and exit non-zero on drift.",
    )
    args = parser.parse_args(argv)
    if args.check:
        return _cmd_check()
    return _cmd_write()


if __name__ == "__main__":
    raise SystemExit(main())
